from langchain_core.tools import tool


# =========================================================
# SEMANTIC LAYER - METRIC DEFINITIONS
# =========================================================

@tool
def get_metric(metric_name: str) -> str:
    """
    Get a business metric definition from the
    MetricMind Semantic Layer.
    """

    metrics = {
        "revenue": "Revenue = Total sales generated by the business.",

        "margin": "Margin = (Revenue - Cost) / Revenue * 100.",

        "churn": "Churn = Percentage of customers who stopped using the service.",

        "cost": "Cost = Total business cost incurred during the period."
    }

    metric = metric_name.lower().strip()

    if metric in metrics:
        return metrics[metric]

    return f"Metric '{metric_name}' is not available in the Semantic Layer."


# =========================================================
# BUSINESS DATA
# =========================================================

@tool
def get_business_data(region: str, quarter: str) -> str:
    """
    Retrieve verified business data for a region and quarter.
    """

    business_data = {

        ("Europe", "Q2"): {
            "revenue": 1000000,
            "cost": 760000,
            "margin": 24
        },

        ("Europe", "Q3"): {
            "revenue": 1100000,
            "cost": 902000,
            "margin": 18
        },

        ("Asia", "Q2"): {
            "revenue": 800000,
            "cost": 560000,
            "margin": 30
        },

        ("Asia", "Q3"): {
            "revenue": 900000,
            "cost": 585000,
            "margin": 35
        }
    }

    region = region.strip().title()
    quarter = quarter.strip().upper()

    key = (region, quarter)

    if key not in business_data:
        return (
            f"No business data available for "
            f"Region={region}, Quarter={quarter}."
        )

    data = business_data[key]

    return f"""
Region: {region}
Quarter: {quarter}

Revenue: ${data['revenue']:,}
Cost: ${data['cost']:,}
Margin: {data['margin']}%
"""


# =========================================================
# BUSINESS COMPARISON
# =========================================================

@tool
def compare_business_data(
    region: str,
    previous_quarter: str,
    current_quarter: str
) -> str:
    """
    Compare verified business data between two quarters.

    All calculations are performed deterministically in Python.
    """

    business_data = {

        ("Europe", "Q2"): {
            "revenue": 1000000,
            "cost": 760000,
            "margin": 24
        },

        ("Europe", "Q3"): {
            "revenue": 1100000,
            "cost": 902000,
            "margin": 18
        },

        ("Asia", "Q2"): {
            "revenue": 800000,
            "cost": 560000,
            "margin": 30
        },

        ("Asia", "Q3"): {
            "revenue": 900000,
            "cost": 585000,
            "margin": 35
        }
    }

    # -----------------------------------------------------
    # Normalize inputs
    # -----------------------------------------------------

    region = region.strip().title()

    previous_quarter = previous_quarter.strip().upper()

    current_quarter = current_quarter.strip().upper()


    # -----------------------------------------------------
    # Create keys
    # -----------------------------------------------------

    previous_key = (region, previous_quarter)

    current_key = (region, current_quarter)


    # -----------------------------------------------------
    # Validate data
    # -----------------------------------------------------

    if previous_key not in business_data:
        return f"No data available for {region} {previous_quarter}."

    if current_key not in business_data:
        return f"No data available for {region} {current_quarter}."


    # -----------------------------------------------------
    # Get data
    # -----------------------------------------------------

    previous = business_data[previous_key]

    current = business_data[current_key]


    # -----------------------------------------------------
    # Calculate absolute changes
    # -----------------------------------------------------

    revenue_change = (
        current["revenue"] -
        previous["revenue"]
    )

    cost_change = (
        current["cost"] -
        previous["cost"]
    )

    margin_change = (
        current["margin"] -
        previous["margin"]
    )


    # -----------------------------------------------------
    # Calculate percentage changes
    # -----------------------------------------------------

    revenue_percentage_change = (
        revenue_change /
        previous["revenue"]
    ) * 100

    cost_percentage_change = (
        cost_change /
        previous["cost"]
    ) * 100


    # -----------------------------------------------------
    # Compare growth rates
    # -----------------------------------------------------

    growth_difference = (
        cost_percentage_change -
        revenue_percentage_change
    )


    # -----------------------------------------------------
    # Determine relationship
    # -----------------------------------------------------

    if revenue_percentage_change > cost_percentage_change:

        growth_relationship = (
            "Revenue grew faster than cost."
        )

    elif revenue_percentage_change < cost_percentage_change:

        growth_relationship = (
            "Cost grew faster than revenue."
        )

    else:

        growth_relationship = (
            "Revenue and cost grew at the same rate."
        )


    # -----------------------------------------------------
    # Determine margin direction
    # -----------------------------------------------------

    if margin_change > 0:

        margin_direction = "Margin increased."

    elif margin_change < 0:

        margin_direction = "Margin decreased."

    else:

        margin_direction = "Margin remained unchanged."


    # =====================================================
    # VERIFIED RESULT
    # =====================================================

    return f"""
VERIFIED BUSINESS ANALYSIS

Region: {region}

Previous Quarter: {previous_quarter}
Revenue: ${previous['revenue']:,}
Cost: ${previous['cost']:,}
Margin: {previous['margin']}%

Current Quarter: {current_quarter}
Revenue: ${current['revenue']:,}
Cost: ${current['cost']:,}
Margin: {current['margin']}%

--------------------------------------------------
VERIFIED CHANGES
--------------------------------------------------

Revenue Change:
${revenue_change:+,}

Revenue Percentage Change:
{revenue_percentage_change:+.2f}%

Cost Change:
${cost_change:+,}

Cost Percentage Change:
{cost_percentage_change:+.2f}%

Margin Change:
{margin_change:+.2f} percentage points

Difference Between Cost Growth and Revenue Growth:
{growth_difference:+.2f} percentage points

--------------------------------------------------
VERIFIED RELATIONSHIP
--------------------------------------------------

{growth_relationship}

{margin_direction}

--------------------------------------------------
INTERPRETATION FROM DATA
--------------------------------------------------

The relationship between revenue growth and cost growth
is determined directly from the calculated percentages.

{growth_relationship}

The margin changed from
{previous['margin']}%
to
{current['margin']}%.

No external business cause is inferred from this data.
"""